version: 2

jobs:
  TestCafe Tests:
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - run: sudo npm i -g yarn
      - run: sudo chmod a+rwx /usr/local/bin/yarn

      - run: yarn --no-progress
      - run: yarn run testcafe remote --hostname localhost --ports 1337,1338 &
      - run: echo Start Browser
      - run: google-chrome --no-sandbox --headless --remote-debugging-port=9220 http://localhost:1337

      - store_test_results:
          path: /tmp/testcafe-test-results

workflows:
  version: 2
  tests:
    jobs:
      - Jest Tests
      - TestCafe Tests
