version: 2

jobs:
  Jest Tests:	
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run: sudo npm i -g yarn
      - run: sudo chmod a+rwx /usr/local/bin/yarn

      - run: yarn --no-progress
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test:ci
      - run: yarn run build:site:docs

  TestCafe Tests:
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - run: sudo npm i -g yarn
      - run: sudo chmod a+rwx /usr/local/bin/yarn

      - run: yarn --no-progress
      - run: yarn run build:watch & sleep 60; yarn run testcafe

      - store_test_results:
          path: /tmp/testcafe-test-results

workflows:
  version: 2
  tests:
    jobs:
      - Jest Tests
      - TestCafe Tests
