version: 2

jobs:
  jest:
    build:
      docker:
        - image: circleci/node:8

      steps:
        - checkout

        - run: sudo npm i -g yarn
        - run: sudo chmod a+rwx /usr/local/bin/yarn

        - run: yarn --no-progress
        - run: yarn run build
        - run: yarn run lint
        - run: yarn run test:ci
        - run: yarn run build:site:docs
  testcafe:
    build:
      docker:
        - image: circleci/node:8-browsers

      steps:
        - checkout

        - run: sudo npm i -g yarn
        - run: sudo chmod a+rwx /usr/local/bin/yarn

        - run: yarn --no-progress
        - run: yarn run testcafe

        - store_test_results:
          path: /tmp/testcafe-test-results
